export const triviaCopy = {
  es: {
    title: "TRIVIA", description: "Cuatro opciones. Una respuesta. ¿Hasta dónde llega tu conocimiento?",
    easy: "Fácil", hard: "Difícil", choose: "Elige tu dificultad", start: "Entrar al reto", resume: "Continuar partida",
    easyDescription: "Grandes momentos y cultura futbolera.", hardDescription: "Un paso más para quienes viven el fútbol.",
    intro: "Sin reloj. La partida acaba al primer fallo.", streak: "Racha", best: "Récord", points: "Puntos ganados", question: "Pregunta",
    correct: "¡Correcto!", incorrect: "Fin de la racha", next: "Siguiente pregunta", again: "Volver a jugar", change: "Cambiar dificultad",
    rightAnswer: "Respuesta correcta", summary: "Tu partida", answered: "Respondidas", accuracy: "Precisión", newBest: "Nueva mejor racha",
    rules: "Cómo se puntúa", rulesText: "Como en Mayor o Menor: cada vez que superas tu récord, sumas tu nueva racha × 10 puntos. Repetir una racha anterior no suma puntos. Cada dificultad tiene su propio récord.",
    cycle: "Las preguntas se barajan sin repetir hasta completar el banco; después empieza otra vuelta. Solo un fallo termina la partida.",
    source: "Ver fuente", loading: "Preparando el reto…", saved: "Tu partida se conserva al cambiar de idioma.",
    storage: "El navegador no permite guardar el progreso. Puedes seguir jugando en esta página.",
  },
  en: {
    title: "TRIVIA", description: "Four options. One answer. How far does your knowledge go?",
    easy: "Easy", hard: "Hard", choose: "Choose your difficulty", start: "Take the challenge", resume: "Resume game",
    easyDescription: "Big moments and football knowledge.", hardDescription: "A step up for those who live football.",
    intro: "No timer. Your first mistake ends the game.", streak: "Streak", best: "Best streak", points: "Points earned", question: "Question",
    correct: "Correct!", incorrect: "Streak over", next: "Next question", again: "Play again", change: "Change difficulty",
    rightAnswer: "Correct answer", summary: "Your game", answered: "Answered", accuracy: "Accuracy", newBest: "New best streak",
    rules: "How scoring works", rulesText: "Just like Higher or Lower: each time you beat your record, you earn your new streak × 10 points. Matching an earlier streak earns no points. Each difficulty has its own record.",
    cycle: "Questions are shuffled without repeats until you complete the question bank, then a new cycle begins. Only a wrong answer ends the game.",
    source: "View source", loading: "Preparing your challenge…", saved: "Your game stays with you when you change language.",
    storage: "Your browser cannot save progress. You can keep playing on this page.",
  },
  fr: {
    title: "TRIVIA", description: "Quatre choix. Une réponse. Jusqu'où vont vos connaissances ?",
    easy: "Facile", hard: "Difficile", choose: "Choisissez votre difficulté", start: "Relever le défi", resume: "Reprendre la partie",
    easyDescription: "Grands moments et culture football.", hardDescription: "Un cran au-dessus pour les passionnés.",
    intro: "Sans chrono. La première erreur termine la partie.", streak: "Série", best: "Record", points: "Points gagnés", question: "Question",
    correct: "Bonne réponse !", incorrect: "Fin de la série", next: "Question suivante", again: "Rejouer", change: "Changer de difficulté",
    rightAnswer: "Bonne réponse", summary: "Votre partie", answered: "Réponses", accuracy: "Précision", newBest: "Nouveau record",
    rules: "Le calcul des points", rulesText: "Comme dans Plus ou Moins : chaque fois que vous battez votre record, vous gagnez votre nouvelle série × 10 points. Égaler une ancienne série ne rapporte rien. Chaque difficulté a son propre record.",
    cycle: "Les questions sont mélangées sans répétition jusqu'à épuisement de la banque, puis un nouveau tour commence. Seule une erreur termine la partie.",
    source: "Voir la source", loading: "Préparation du défi…", saved: "Votre partie est conservée quand vous changez de langue.",
    storage: "Votre navigateur ne peut pas sauvegarder la progression. Vous pouvez continuer sur cette page.",
  },
};
