export const triviaCopy = {
  es: {
    title: "TRIVIA", description: "Cuatro opciones. Una respuesta. ¿Hasta dónde llega tu conocimiento?",
    easy: "Fácil", hard: "Difícil", choose: "Elige tu dificultad", start: "Entrar al reto", resume: "Continuar partida",
    easyDescription: "Grandes momentos y cultura futbolera.", hardDescription: "Un paso más para quienes viven el fútbol.",
    timed: "Contrarreloj", timedDescription: "60 segundos. Preguntas fáciles y difíciles. Un fallo y termina.", timeUp: "¡Tiempo cumplido!", timeLeft: "Tiempo restante",
    timedRules: "Contrarreloj mezcla ambas dificultades y termina al primer fallo o a los 60 segundos. Tiene su propio récord y aplica la misma regla de puntos. El reloj sigue al cambiar de modo, idioma o pestaña.",
    intro: "Elige tu reto. La partida acaba al primer fallo.", streak: "Racha", best: "Récord", points: "Puntos ganados", question: "Pregunta",
    correct: "¡Correcto!", incorrect: "Fin de la racha", next: "Siguiente pregunta", again: "Volver a jugar", change: "Cambiar modo",
    rightAnswer: "Respuesta correcta", summary: "Tu partida", answered: "Respondidas", accuracy: "Precisión", newBest: "Nueva mejor racha",
    rules: "Cómo se puntúa", rulesText: "Como en Mayor o Menor: cada vez que superas tu récord, sumas tu nueva racha × 10 puntos. Repetir una racha anterior no suma puntos. Cada dificultad tiene su propio récord.",
    cycle: "Las preguntas se barajan sin repetir hasta completar el banco; después empieza otra vuelta. En fácil y difícil no hay límite de tiempo.",
    source: "Ver fuente", loading: "Preparando el reto…",
    storage: "El navegador no permite guardar el progreso. Puedes seguir jugando en esta página.",
  },
  en: {
    title: "TRIVIA", description: "Four options. One answer. How far does your knowledge go?",
    easy: "Easy", hard: "Hard", choose: "Choose your difficulty", start: "Take the challenge", resume: "Resume game",
    easyDescription: "Big moments and football knowledge.", hardDescription: "A step up for those who live football.",
    timed: "Time attack", timedDescription: "60 seconds. Easy and hard questions. One mistake ends it.", timeUp: "Time’s up!", timeLeft: "Time left",
    timedRules: "Time attack mixes both difficulties and ends at the first mistake or after 60 seconds. It has its own record and uses the same scoring rule. The clock keeps running when you change mode, language or tab.",
    intro: "Choose your challenge. Your first mistake ends the game.", streak: "Streak", best: "Best streak", points: "Points earned", question: "Question",
    correct: "Correct!", incorrect: "Streak over", next: "Next question", again: "Play again", change: "Change mode",
    rightAnswer: "Correct answer", summary: "Your game", answered: "Answered", accuracy: "Accuracy", newBest: "New best streak",
    rules: "How scoring works", rulesText: "Just like Higher or Lower: each time you beat your record, you earn your new streak × 10 points. Matching an earlier streak earns no points. Each difficulty has its own record.",
    cycle: "Questions are shuffled without repeats until you complete the question bank, then a new cycle begins. Easy and hard have no time limit.",
    source: "View source", loading: "Preparing your challenge…",
    storage: "Your browser cannot save progress. You can keep playing on this page.",
  },
  fr: {
    title: "TRIVIA", description: "Quatre choix. Une réponse. Jusqu'où vont vos connaissances ?",
    easy: "Facile", hard: "Difficile", choose: "Choisissez votre difficulté", start: "Relever le défi", resume: "Reprendre la partie",
    easyDescription: "Grands moments et culture football.", hardDescription: "Un cran au-dessus pour les passionnés.",
    timed: "Contre-la-montre", timedDescription: "60 secondes. Questions faciles et difficiles. Une erreur et c’est fini.", timeUp: "Temps écoulé !", timeLeft: "Temps restant",
    timedRules: "Le contre-la-montre mélange les deux difficultés et se termine à la première erreur ou après 60 secondes. Il possède son propre record et suit la même règle de points. Le chrono continue si vous changez de mode, de langue ou d’onglet.",
    intro: "Choisissez votre défi. La première erreur termine la partie.", streak: "Série", best: "Record", points: "Points gagnés", question: "Question",
    correct: "Bonne réponse !", incorrect: "Fin de la série", next: "Question suivante", again: "Rejouer", change: "Changer de mode",
    rightAnswer: "Bonne réponse", summary: "Votre partie", answered: "Réponses", accuracy: "Précision", newBest: "Nouveau record",
    rules: "Le calcul des points", rulesText: "Comme dans Plus ou Moins : chaque fois que vous battez votre record, vous gagnez votre nouvelle série × 10 points. Égaler une ancienne série ne rapporte rien. Chaque difficulté a son propre record.",
    cycle: "Les questions sont mélangées sans répétition jusqu'à épuisement de la banque, puis un nouveau tour commence. Les modes facile et difficile sont sans limite de temps.",
    source: "Voir la source", loading: "Préparation du défi…",
    storage: "Votre navigateur ne peut pas sauvegarder la progression. Vous pouvez continuer sur cette page.",
  },
};
