import type { Position } from './engine';
export type GridLocale = 'es' | 'en' | 'fr';
export const gridCopy = {
  "es": {
    "description": "16 casillas. 16 futbolistas. Cuanto antes completes el grid, más puntos ganarás.",
    "choose": "Elige tu desafío",
    "easy": "Fácil",
    "hard": "Difícil",
    "countryClub": "Nacionalidad × club",
    "countryPosition": "Nacionalidad × posición",
    "clubClub": "Club × club",
    "easyText": "Cruza nacionalidades con clubes o posiciones.",
    "hardText": "Encuentra jugadores que hayan disputado partidos oficiales en ambos clubes.",
    "start": "Empezar",
    "resume": "Continuar",
    "loading": "Cargando tu grid…",
    "login": "Inicia sesión para jugar",
    "loginText": "Tus partidas, puntos y límite diario se guardan en tu cuenta, también al cambiar de dispositivo.",
    "unavailable": "Football Grid no está disponible ahora. No se ha iniciado ninguna partida nueva.",
    "retry": "Reintentar",
    "error": "No se pudo conectar. Reintenta para recuperar tu partida; los puntos disponibles siguen bajando.",
    "rules": "Reglas y puntuación",
    "result": "Resultado",
    "complete": "Grid completo",
    "expired": "Tiempo agotado",
    "surrendered": "Te has rendido",
    "reward": "Puntos por completar",
    "penalty": "Por rendirte",
    "seconds": "segundos",
    "points": "Puntos",
    "total": "Tus puntos en este modo",
    "filled": "Casillas",
    "daily": "Partidas de hoy",
    "limit": "Has completado tus tres partidas de hoy en este modo.",
    "reset": "El límite se reinicia a medianoche (Europe/Madrid).",
    "rulesText": "Completa las 16 casillas con futbolistas distintos. Busca y selecciona un nombre: puedes intentarlo cuantas veces quieras dentro del tiempo. Para un club cuenta al menos un partido oficial con el primer equipo; para un país cuenta la nacionalidad, no la selección representada.",
    "scoring": "Fácil empieza en 5.000 puntos y difícil en 10.000. Los puntos disponibles bajan proporcionalmente al tiempo: puntuación inicial × tiempo restante ÷ 10 minutos. A los 5 minutos quedan 2.500 o 5.000 puntos. Al completar las 16 casillas ganas los puntos restantes, redondeados hacia abajo al entero. A los 10 minutos termina la partida con 0 puntos. Rendirse resta 20 en fácil o 50 en difícil. No hay puntos parciales ni penalización por respuestas incorrectas. El saldo de cada modo nunca baja de cero y suma al total de tu cuenta.",
    "quota": "Tres partidas diarias por dificultad. Ganar o agotar el tiempo consume una partida; rendirse antes de que termine el tiempo no consume el límite. El día de la partida es el día en que la empiezas. Salir, recargar o cambiar de idioma no detiene la bajada de puntos.",
    "editRule": "Puedes seleccionar una casilla resuelta para cambiar su jugador. Ningún futbolista puede ocupar dos casillas a la vez.",
    "data": "Leyendas, incluido Messi, y jugadores de las plantillas actuales de los 26 clubes europeos Premium internacional y Élite internacional de Modo Carrera. En fácil aparecen clubes europeos; en difícil también cuentan clubes históricos no europeos de esas categorías. Cada club requiere partidos oficiales acreditados en el catálogo.",
    "catalog": "futbolistas en el catálogo",
    "search": "Busca un futbolista",
    "searchHint": "Escribe su nombre y selecciona una sugerencia. No se repiten futbolistas.",
    "empty": "No hay coincidencias en el catálogo disponible.",
    "cell": "Casilla",
    "close": "Cerrar búsqueda",
    "change": "Cambiar jugador",
    "correct": "¡Correcto!",
    "incorrect": "Ese jugador no cumple las dos condiciones.",
    "duplicate": "Ese jugador ya está en el grid.",
    "filledMessage": "Esta casilla ya está resuelta.",
    "surrender": "Rendirme",
    "surrenderConfirm": "¿Rendirte? Se aplicará la penalización indicada; esta partida no consumirá el límite diario.",
    "confirm": "Sí, rendirme",
    "cancel": "Seguir jugando",
    "again": "Otra partida",
    "modes": "Cambiar de modo",
    "time": "Tiempo restante",
    "warning": "Quedan muy pocos puntos disponibles.",
    "summary": "Resumen de la partida",
    "achievements": "Logros de Football Grid",
    "achievementEasy": "Primer grid fácil",
    "achievementHard": "Primer grid difícil",
    "achievementBoth": "Domina ambos modos",
    "achievementTen": "Diez grids completos",
    "earned": "Conseguido",
    "pending": "Pendiente",
    "available": "Puntos disponibles",
    "maxTime": "Máximo 10 minutos",
    "currentStreak": "Racha actual",
    "bestStreak": "Mejor racha",
    "bestTime": "Récord de resolución",
    "history": "Últimas partidas",
    "historyEmpty": "Todavía no hay partidas terminadas en este modo.",
    "resolution": "Tiempo de resolución",
    "achievementStreak": "Tres grids seguidos",
    "achievementFast": "Un grid en cinco minutos",
    "updateRequired": "Estamos actualizando las reglas. Las partidas nuevas estarán disponibles al terminar.",
    "legacyRound": "Esta partida conserva las reglas anteriores con las que empezó.",
    "recordRules": "Las rachas cuentan grids completos consecutivos por dificultad y se mantienen entre días. Rendirse o agotar los 10 minutos rompe la racha; una respuesta incorrecta no. Se guardan la mejor racha y el menor tiempo de resolución. Logros: tres victorias seguidas y resolver un grid en cinco minutos o menos."
  },
  "en": {
    "description": "16 cells. 16 footballers. The faster you finish, the more points you earn.",
    "choose": "Choose your challenge",
    "easy": "Easy",
    "hard": "Hard",
    "countryClub": "Nationality × club",
    "countryPosition": "Nationality × position",
    "clubClub": "Club × club",
    "easyText": "Match nationalities with clubs or positions.",
    "hardText": "Find players who have played official matches for both clubs.",
    "start": "Start",
    "resume": "Resume",
    "loading": "Loading your grid…",
    "login": "Sign in to play",
    "loginText": "Your games, points and daily limit are saved to your account, including across devices.",
    "unavailable": "Football Grid is unavailable right now. No new game has been started.",
    "retry": "Retry",
    "error": "Could not connect. Retry to recover your game; available points keep decreasing.",
    "rules": "Rules and scoring",
    "result": "Result",
    "complete": "Grid complete",
    "expired": "Time is up",
    "surrendered": "You surrendered",
    "reward": "Points for completing",
    "penalty": "For surrendering",
    "seconds": "seconds",
    "points": "Points",
    "total": "Your points in this mode",
    "filled": "Cells",
    "daily": "Today’s games",
    "limit": "You have used your three games in this mode today.",
    "reset": "The limit resets at midnight (Europe/Madrid).",
    "rulesText": "Fill all 16 cells with different footballers. Search and select a name: you have unlimited attempts within the time limit. Clubs require at least one official first-team appearance; countries use nationality, not the national team represented.",
    "scoring": "Easy starts at 5,000 points and Hard at 10,000. Available points decrease proportionally with time: starting points × remaining time ÷ 10 minutes. After 5 minutes, 2,500 or 5,000 points remain. Complete all 16 cells to earn the remaining points, rounded down to a whole number. After 10 minutes the game ends with 0 points. Surrendering deducts 20 in Easy or 50 in Hard. No partial points or penalties for incorrect answers. Each mode’s balance never drops below zero and contributes to your account total.",
    "quota": "Three daily games per difficulty. Winning or running out of time uses one game; surrendering before time runs out does not use the limit. A game counts towards the day it started. Leaving, reloading or changing language does not pause the decrease in points.",
    "editRule": "Select a completed cell to change its player. A footballer cannot occupy two cells at the same time.",
    "data": "Legends, including Messi, and current squad members of the 26 European Premium International and International Elite clubs in Career Mode. Easy uses European clubs; Hard also includes historical non-European clubs in those categories. Each club requires official appearances documented in the catalog.",
    "catalog": "footballers in the catalog",
    "search": "Search for a footballer",
    "searchHint": "Type a name and select a suggestion. Each footballer can appear only once.",
    "empty": "No matches in the available catalog.",
    "cell": "Cell",
    "close": "Close search",
    "change": "Change player",
    "correct": "Correct!",
    "incorrect": "This player does not meet both conditions.",
    "duplicate": "This player is already in the grid.",
    "filledMessage": "This cell is already complete.",
    "surrender": "Surrender",
    "surrenderConfirm": "Surrender? The stated penalty applies; this game will not use your daily limit.",
    "confirm": "Yes, surrender",
    "cancel": "Keep playing",
    "again": "Another game",
    "modes": "Change mode",
    "time": "Time remaining",
    "warning": "Very few points remain.",
    "summary": "Game summary",
    "achievements": "Football Grid achievements",
    "achievementEasy": "First easy grid",
    "achievementHard": "First hard grid",
    "achievementBoth": "Master both modes",
    "achievementTen": "Ten completed grids",
    "earned": "Unlocked",
    "pending": "Locked",
    "available": "Available points",
    "maxTime": "10-minute maximum",
    "currentStreak": "Current streak",
    "bestStreak": "Best streak",
    "bestTime": "Fastest completion",
    "history": "Recent games",
    "historyEmpty": "No completed games in this mode yet.",
    "resolution": "Completion time",
    "achievementStreak": "Three grids in a row",
    "achievementFast": "A grid in five minutes",
    "updateRequired": "The rules are being updated. New games will be available afterwards.",
    "legacyRound": "This game keeps the previous rules under which it started.",
    "recordRules": "Streaks count consecutive completed grids per difficulty and carry across days. Surrendering or reaching 10 minutes breaks the streak; incorrect answers do not. Your best streak and fastest completion are saved. Achievements: three consecutive wins and a grid in five minutes or less."
  },
  "fr": {
    "description": "16 cases. 16 footballeurs. Plus vous terminez vite, plus vous gagnez de points.",
    "choose": "Choisissez votre défi",
    "easy": "Facile",
    "hard": "Difficile",
    "countryClub": "Nationalité × club",
    "countryPosition": "Nationalité × poste",
    "clubClub": "Club × club",
    "easyText": "Croisez les nationalités avec les clubs ou les postes.",
    "hardText": "Trouvez des joueurs ayant disputé des matchs officiels pour les deux clubs.",
    "start": "Commencer",
    "resume": "Reprendre",
    "loading": "Chargement de votre grille…",
    "login": "Connectez-vous pour jouer",
    "loginText": "Vos parties, vos points et votre limite quotidienne sont enregistrés sur votre compte, même sur un autre appareil.",
    "unavailable": "Football Grid est indisponible pour le moment. Aucune nouvelle partie n’a été lancée.",
    "retry": "Réessayer",
    "error": "Connexion impossible. Réessayez ; les points disponibles continuent de diminuer.",
    "rules": "Règles et points",
    "result": "Résultat",
    "complete": "Grille complétée",
    "expired": "Temps écoulé",
    "surrendered": "Vous avez abandonné",
    "reward": "Points pour terminer",
    "penalty": "En cas d’abandon",
    "seconds": "secondes",
    "points": "Points",
    "total": "Vos points dans ce mode",
    "filled": "Cases",
    "daily": "Parties du jour",
    "limit": "Vous avez utilisé vos trois parties du jour dans ce mode.",
    "reset": "La limite est réinitialisée à minuit (Europe/Madrid).",
    "rulesText": "Remplissez les 16 cases avec des footballeurs différents. Recherchez et sélectionnez un nom : les essais sont illimités dans le temps imparti. Un club exige au moins un match officiel en équipe première ; un pays correspond à la nationalité, pas à la sélection représentée.",
    "scoring": "Le mode facile commence à 5 000 points et le difficile à 10 000. Les points diminuent proportionnellement au temps : points initiaux × temps restant ÷ 10 minutes. Après 5 minutes, il reste 2 500 ou 5 000 points. Complétez les 16 cases pour gagner les points restants, arrondis à l’entier inférieur. Après 10 minutes, la partie se termine avec 0 point. Abandonner retire 20 points en facile ou 50 en difficile. Aucun point partiel ni pénalité pour une réponse incorrecte. Le solde de chaque mode ne descend jamais sous zéro et contribue au total du compte.",
    "quota": "Trois parties par jour et par difficulté. Gagner ou laisser expirer le temps consomme une partie ; abandonner avant la fin du temps ne consomme pas la limite. La partie compte pour le jour où elle a commencé. Quitter, recharger ou changer de langue ne suspend pas la diminution des points.",
    "editRule": "Sélectionnez une case remplie pour changer son joueur. Un footballeur ne peut pas occuper deux cases à la fois.",
    "data": "Légendes, dont Messi, et joueurs des effectifs actuels des 26 clubs européens Premium international et Élite internationale du mode Carrière. Le mode facile utilise les clubs européens ; le mode difficile inclut aussi les anciens clubs non européens de ces catégories. Chaque club exige des matchs officiels attestés dans le catalogue.",
    "catalog": "footballeurs dans le catalogue",
    "search": "Rechercher un footballeur",
    "searchHint": "Saisissez un nom et sélectionnez une suggestion. Chaque joueur ne peut apparaître qu’une fois.",
    "empty": "Aucun résultat dans le catalogue disponible.",
    "cell": "Case",
    "close": "Fermer la recherche",
    "change": "Changer de joueur",
    "correct": "Bonne réponse !",
    "incorrect": "Ce joueur ne remplit pas les deux conditions.",
    "duplicate": "Ce joueur figure déjà dans la grille.",
    "filledMessage": "Cette case est déjà remplie.",
    "surrender": "Abandonner",
    "surrenderConfirm": "Abandonner ? La pénalité indiquée sera appliquée ; cette partie ne consommera pas votre limite quotidienne.",
    "confirm": "Oui, abandonner",
    "cancel": "Continuer à jouer",
    "again": "Nouvelle partie",
    "modes": "Changer de mode",
    "time": "Temps restant",
    "warning": "Il reste très peu de points.",
    "summary": "Résumé de la partie",
    "achievements": "Succès Football Grid",
    "achievementEasy": "Première grille facile",
    "achievementHard": "Première grille difficile",
    "achievementBoth": "Maîtrisez les deux modes",
    "achievementTen": "Dix grilles complétées",
    "earned": "Débloqué",
    "pending": "Verrouillé",
    "available": "Points disponibles",
    "maxTime": "10 minutes maximum",
    "currentStreak": "Série en cours",
    "bestStreak": "Meilleure série",
    "bestTime": "Meilleur temps",
    "history": "Dernières parties",
    "historyEmpty": "Aucune partie terminée dans ce mode.",
    "resolution": "Temps de résolution",
    "achievementStreak": "Trois grilles de suite",
    "achievementFast": "Une grille en cinq minutes",
    "updateRequired": "Les règles sont en cours de mise à jour. Les nouvelles parties seront disponibles ensuite.",
    "legacyRound": "Cette partie conserve les anciennes règles avec lesquelles elle a commencé.",
    "recordRules": "Les séries comptent les grilles terminées consécutivement par difficulté, même sur plusieurs jours. Abandonner ou atteindre 10 minutes interrompt la série ; une réponse incorrecte ne l’interrompt pas. La meilleure série et le meilleur temps sont conservés. Succès : trois victoires consécutives et une grille en cinq minutes ou moins."
  }
};
export const positionCopy: Record<GridLocale, Record<Position,string>> = {
  "es": {
    "Goalkeeper": "Portero",
    "Defender": "Defensa",
    "Midfielder": "Centrocampista",
    "Attacker": "Delantero"
  },
  "en": {
    "Goalkeeper": "Goalkeeper",
    "Defender": "Defender",
    "Midfielder": "Midfielder",
    "Attacker": "Forward"
  },
  "fr": {
    "Goalkeeper": "Gardien",
    "Defender": "Défenseur",
    "Midfielder": "Milieu",
    "Attacker": "Attaquant"
  }
};
