import type { Locale } from "@/lib/i18n";

type Game = "higherLower" | "wordle" | "badge";

const copy = {
  es: {
    heading: "Guía del juego", rules: "Reglas", tips: "Consejos", data: "Datos y metodología", faq: "Preguntas frecuentes",
    higherLower: { title: "Cómo jugar a Mayor o Menor", intro: "Compara temporadas concretas de dos futbolistas y decide si el jugador de la derecha marcó más o menos goles. Aquí importa la campaña indicada, no el prestigio de toda su carrera.", rules: ["Observa la temporada y los goles del jugador de referencia.", "Elige Más o Menos para el segundo futbolista.", "Cada acierto alarga la racha; el primer error termina la partida."], tips: "Valora el club, la temporada, las lesiones y el número aproximado de partidos. Usa la cifra revelada como referencia antes de responder.", data: "Las rondas utilizan registros de temporadas de clubes con jugador, equipo, apariciones y goles. Se excluyen selecciones y temporadas sin datos suficientes.", question: "¿Se cuentan goles con la selección?", answer: "No. Esta modalidad compara exclusivamente temporadas de clubes." },
    wordle: { title: "Cómo jugar a Adivina el jugador", intro: "Descubre el nombre futbolístico oculto en seis intentos. El verde marca una letra bien colocada, el amarillo una letra presente en otra posición y el gris una letra ausente.", rules: ["Escribe un nombre válido con la longitud indicada.", "Usa la información de colores para el siguiente intento.", "Las pistas y la rendición reducen la puntuación final."], tips: "Empieza combinando vocales y consonantes frecuentes. Conserva las letras verdes y mueve las amarillas a posiciones todavía no probadas.", data: "La selección incluye futbolistas con un nombre deportivo inequívoco. Se normalizan mayúsculas y tildes para evitar errores debidos al teclado.", question: "¿Las tildes cuentan como letras diferentes?", answer: "No. El juego normaliza las tildes al comprobar cada respuesta." },
    badge: { title: "Cómo jugar a Adivina el Escudo", intro: "Identifica un club a partir de su escudo pixelado. Cada fallo aumenta la resolución y revela nuevos colores, formas y detalles; dispones de seis intentos.", rules: ["Observa la silueta y los colores iniciales.", "Busca y selecciona un club de las sugerencias.", "Acierta cuanto antes para conseguir más puntos."], tips: "Empieza por la combinación de colores y la forma exterior. Después busca iniciales, coronas, animales o franjas cuando aumente la resolución.", data: "Se utilizan clubes activos con una imagen identificable. Se excluyen selecciones, filiales y equipos juveniles; la pixelación se genera en el navegador.", question: "¿Aparecen selecciones nacionales?", answer: "No. Esta modalidad está dedicada exclusivamente a clubes." },
  },
  en: {
    heading: "Game guide", rules: "Rules", tips: "Tips", data: "Data and methodology", faq: "Frequently asked questions",
    higherLower: { title: "How to play Higher or Lower", intro: "Compare two specific club seasons and decide whether the player on the right scored more or fewer goals. The selected season matters, not the player's overall reputation.", rules: ["Check the reference player's season and goals.", "Choose Higher or Lower for the second player.", "Each correct answer extends the streak; one mistake ends it."], tips: "Consider the club, season, injuries and approximate appearances. Use the revealed total as your anchor before answering.", data: "Rounds use club-season records containing player, team, appearances and goals. International records and incomplete seasons are excluded.", question: "Are international goals included?", answer: "No. This game compares club seasons only." },
    wordle: { title: "How to play Guess the Player", intro: "Find the hidden football name in six attempts. Green means the right letter and position, yellow means the letter appears elsewhere, and grey means it is absent.", rules: ["Enter a valid name of the displayed length.", "Use the colour feedback in your next attempt.", "Hints and giving up reduce the final score."], tips: "Open with common vowels and consonants. Keep green letters fixed and move yellow letters to positions you have not tested.", data: "The pool contains footballers with an unambiguous sporting name. Capitalisation and accents are normalised to avoid keyboard-related errors.", question: "Do accents count as different letters?", answer: "No. Accents are normalised when an answer is checked." },
    badge: { title: "How to play Guess the Badge", intro: "Identify a club from a pixelated badge. Every miss raises the resolution and reveals more colours, shapes and details; you have six attempts.", rules: ["Study the initial outline and colours.", "Search for and select a club from the suggestions.", "Answer early to earn more points."], tips: "Start with the colour combination and outer shape. As the image clears, look for initials, crowns, animals or stripes.", data: "The pool uses active clubs with identifiable artwork. National teams, reserve sides and youth teams are excluded; pixelation is generated in the browser.", question: "Do national teams appear?", answer: "No. This mode is exclusively about clubs." },
  },
  fr: {
    heading: "Guide du jeu", rules: "Règles", tips: "Conseils", data: "Données et méthode", faq: "Questions fréquentes",
    higherLower: { title: "Comment jouer à Plus ou Moins", intro: "Comparez deux saisons précises en club et déterminez si le joueur de droite a marqué plus ou moins de buts. La saison indiquée compte, pas la réputation générale.", rules: ["Observez la saison et les buts du joueur de référence.", "Choisissez Plus ou Moins pour le second joueur.", "Chaque bonne réponse prolonge la série ; une erreur y met fin."], tips: "Tenez compte du club, de la saison, des blessures et du nombre approximatif de matchs. Utilisez le total révélé comme repère.", data: "Les manches utilisent des données par saison de club : joueur, équipe, apparitions et buts. Les sélections et saisons incomplètes sont exclues.", question: "Les buts en sélection sont-ils comptés ?", answer: "Non. Ce jeu compare uniquement les saisons en club." },
    wordle: { title: "Comment jouer à Devinez le joueur", intro: "Trouvez le nom footballistique caché en six essais. Le vert indique la bonne lettre au bon endroit, le jaune une lettre ailleurs et le gris une lettre absente.", rules: ["Saisissez un nom valide de la longueur indiquée.", "Utilisez les couleurs pour l'essai suivant.", "Les indices et l'abandon réduisent le score final."], tips: "Commencez avec des voyelles et consonnes fréquentes. Gardez les lettres vertes et déplacez les jaunes vers des positions non testées.", data: "La sélection comprend des joueurs au nom sportif non ambigu. Les majuscules et accents sont normalisés pour éviter les erreurs de clavier.", question: "Les accents comptent-ils comme des lettres différentes ?", answer: "Non. Les accents sont normalisés lors de la vérification." },
    badge: { title: "Comment jouer à Devinez l'écusson", intro: "Identifiez un club à partir de son écusson pixelisé. Chaque erreur augmente la résolution et révèle davantage de couleurs, formes et détails ; vous avez six essais.", rules: ["Observez la silhouette et les couleurs initiales.", "Recherchez puis sélectionnez un club proposé.", "Répondez tôt pour gagner davantage de points."], tips: "Commencez par les couleurs et la forme extérieure. Puis cherchez initiales, couronnes, animaux ou bandes à mesure que l'image se précise.", data: "La sélection utilise des clubs actifs aux visuels identifiables. Les sélections, réserves et équipes de jeunes sont exclues ; la pixellisation est générée dans le navigateur.", question: "Les sélections nationales apparaissent-elles ?", answer: "Non. Ce mode est exclusivement consacré aux clubs." },
  },
} as const;

export default function GameGuide({ locale, game }: { locale: Locale; game: Game }) {
  const labels = copy[locale]; const c = labels[game];
  return <section className="game-guide"><div className="game-guide-intro"><span className="eyebrow">{labels.heading}</span><h2>{c.title}</h2><p>{c.intro}</p></div><div className="game-guide-grid"><article className="game-guide-card"><h3>{labels.rules}</h3><ol>{c.rules.map((rule)=><li key={rule}>{rule}</li>)}</ol></article><article className="game-guide-card"><h3>{labels.tips}</h3><p>{c.tips}</p></article><article className="game-guide-card"><h3>{labels.data}</h3><p>{c.data}</p></article></div><div className="game-faq"><h2>{labels.faq}</h2><details><summary>{c.question}</summary><p>{c.answer}</p></details></div></section>;
}
