export const locales = ["es", "en", "fr"] as const;
export type Locale = (typeof locales)[number];
export const defaultLocale: Locale = "es";

export function isLocale(value: string): value is Locale {
  return locales.includes(value as Locale);
}

export function localizedPath(locale: Locale, path = "") {
  return `/${locale}${path === "/" ? "" : path}`;
}

export const dictionaries = {
  es: {
    languageName: "Español", nav: { home: "Inicio", games: "Juegos", beta: "Beta", main: "Navegación principal", legal: "Información legal", privacy: "Privacidad", cookies: "Cookies", notice: "Aviso legal", feedback: "Feedback", language: "Idioma" },
    meta: { title: "Juegos de fútbol online", description: "Juegos de fútbol online para poner a prueba tus conocimientos: Adivina el jugador, Mayor o Menor, Adivina el Escudo y más.", shortDescription: "Pon a prueba cuánto sabes de fútbol con retos y minijuegos gratuitos." },
    home: { alt: "10theGOAT · Juegos de fútbol online", eyebrow: "10theGOAT Arena", title: "El fútbol también se juega aquí.", intro: "Elige tu reto, demuestra cuánto sabes de fútbol y supera tu mejor marca.", play: "Empezar a jugar", beta: "Explorar juegos", version: "Arena", games: "Juegos", all: "Ver todos →" },
    catalog: { title: "Todos los juegos" },
    status: { available: "Ya disponible", soon: "Próximamente" },
    games: {
      higherLower: { title: "Mayor o Menor", description: "Compara estadísticas de futbolistas y encadena la mayor racha posible.", meta: "Compara goles de temporadas reales y encadena la mayor racha posible.", eyebrow: "Estadísticas reales · clubes", intro: "Compara temporadas reales. Acierta si el futbolista de la derecha marcó más o menos goles que el de la izquierda y construye tu racha." },
      wordle: { title: "Adivina el jugador", description: "Wordle futbolero: seis intentos para descubrir el nombre futbolístico del jugador letra a letra.", meta: "Wordle futbolero: descubre el nombre del jugador en seis intentos.", eyebrow: "Wordle futbolero", intro: "Seis intentos. Una letra verde está en su sitio; una amarilla está en el nombre, pero en otra posición. Las tildes no cuentan." },
      grid: { title: "Football Grid", description: "Cruza clubes, selecciones y condiciones para encontrar jugadores válidos." },
      career: { title: "Modo Carrera", description: "Crea un jugador y simula toda su carrera, fichajes, títulos, selección y legado." },
      eleven: { title: "Mi XI", description: "Construye tu once ideal con presupuesto, restricciones y cartas de jugador." },
      badge: { title: "Adivina el Escudo", description: "Reconoce el club por un escudo extremadamente pixelado que se aclara con cada intento.", meta: "Reconoce el club mientras su escudo se desvela intento a intento.", eyebrow: "Escudos de clubes", intro: "El escudo empieza casi irreconocible. Cada fallo reduce el pixelado. Tienes seis intentos para descubrir el club." },
      placeholder: { body: "La ruta ya está preparada. Este módulo se conectará al núcleo común de datos de 10theGOAT.", label: "⚽ Módulo en construcción" }
    },
    beta: { title: "10theGOAT está en Beta", intro: "La web ya se puede jugar, pero seguimos afinando nombres, escudos, puntuaciones, rendimiento y experiencia móvil.", playable: "Jugable ahora", playableText: "Adivina el jugador, Mayor o Menor y Adivina el Escudo.", development: "En desarrollo", developmentText: "Football Grid, Modo Carrera, Mi XI, cuentas de usuario y rankings globales.", scores: "Puntuaciones", scoresText: "Durante esta Beta se guardan en este navegador. Al introducir cuentas, pasarán a estar vinculadas al usuario.", bug: "¿Has encontrado un fallo?", bugText: "Cuéntanos qué estabas haciendo, qué navegador usabas y, si puedes, adjunta una captura.", report: "Reportar en GitHub", back: "← Volver a los juegos" },
    legal: {
      eyebrow: "Información Beta",
      privacy: { title: "Privacidad", lead: "10theGOAT está en fase Beta y actualmente no dispone de cuentas de usuario.", sections: [["Datos de juego", "Las puntuaciones y estadísticas locales de los juegos se guardan en el almacenamiento local de tu navegador (localStorage). Puedes eliminarlas borrando los datos del sitio en tu navegador."], ["Base de datos e infraestructura", "Los juegos consultan datos futbolísticos almacenados en Supabase. La infraestructura de alojamiento y base de datos puede tratar datos técnicos necesarios para servir las peticiones, como direcciones IP, registros técnicos y datos de seguridad."], ["Analítica y publicidad", "Esta versión Beta no incorpora por defecto herramientas propias de analítica publicitaria ni perfiles de usuario."], ["Antes del lanzamiento definitivo", "La información identificativa y de contacto del responsable del sitio deberá completarse en la versión legal definitiva antes de la apertura comercial o monetizada."]] },
      cookies: { title: "Cookies y almacenamiento local", sections: [["", "La aplicación 10theGOAT no instala actualmente cookies publicitarias propias ni cookies de analítica dentro de esta versión Beta."], ["localStorage", "Los juegos utilizan almacenamiento local del navegador para conservar puntuaciones, récords y estadísticas de la Beta. No es una cookie y no se envía automáticamente al servidor con cada petición."], ["Servicios técnicos", "El proveedor de alojamiento o servicios externos necesarios para servir la web pueden utilizar mecanismos técnicos propios conforme a sus políticas."], ["Futuras funciones", "Si añadimos analítica, publicidad, cuentas o tecnologías que requieran consentimiento, actualizaremos esta información y, cuando corresponda, incorporaremos un sistema de consentimiento."]] },
      notice: { title: "Aviso legal", sections: [["", "10theGOAT es un proyecto de juegos de fútbol online actualmente en fase Beta."], ["Contenido", "Los nombres, marcas, escudos e imágenes de terceros pertenecen a sus respectivos titulares. Su presencia en la Beta tiene finalidad identificativa dentro de los juegos."], ["Disponibilidad", "Al tratarse de una Beta, funciones, puntuaciones, datos y reglas pueden cambiar, reiniciarse o dejar de estar disponibles durante el desarrollo."], ["Datos del titular", "PENDIENTE DE REVISIÓN HUMANA: antes de abrir públicamente el dominio debe completarse aquí la identificación legal y un canal de contacto adecuado del responsable del sitio."]] }
    },
    notFound: { title: "Fuera de juego.", body: "Esta página no existe o todavía no ha salido al campo.", back: "Volver al inicio" }
  },
  en: {
    languageName: "English", nav: { home: "Home", games: "Games", beta: "Beta", main: "Main navigation", legal: "Legal information", privacy: "Privacy", cookies: "Cookies", notice: "Legal notice", feedback: "Feedback", language: "Language" },
    meta: { title: "Online football games", description: "Online football games that put your knowledge to the test: Guess the Player, Higher or Lower, Guess the Badge and more.", shortDescription: "Put your football knowledge to the test with free challenges and mini-games." },
    home: { alt: "10theGOAT · Online football games", eyebrow: "10theGOAT Arena", title: "Football is played here too.", intro: "Choose your challenge, prove your football knowledge and beat your best score.", play: "Start playing", beta: "Explore games", version: "Arena", games: "Games", all: "View all →" },
    catalog: { title: "All games" }, status: { available: "Available now", soon: "Coming soon" },
    games: {
      higherLower: { title: "Higher or Lower", description: "Compare footballers' stats and build the longest streak you can.", meta: "Compare goals from real seasons and build the longest streak you can.", eyebrow: "Real stats · clubs", intro: "Compare real seasons. Decide whether the player on the right scored more or fewer goals than the player on the left and build your streak." },
      wordle: { title: "Guess the Player", description: "Football Wordle: six attempts to reveal the player's football name letter by letter.", meta: "Football Wordle: guess the player in six attempts.", eyebrow: "Football Wordle", intro: "Six attempts. A green letter is in the right place; a yellow one is in the name but in another position. Accents do not count." },
      grid: { title: "Football Grid", description: "Combine clubs, national teams and conditions to find valid players." }, career: { title: "Career Mode", description: "Create a player and simulate their full career, transfers, trophies, national team and legacy." }, eleven: { title: "My XI", description: "Build your ideal eleven with a budget, restrictions and player cards." },
      badge: { title: "Guess the Badge", description: "Identify the club from a heavily pixelated badge that becomes clearer after every attempt.", meta: "Identify the club as its badge is gradually revealed.", eyebrow: "Club badges", intro: "The badge starts almost unrecognisable. Each miss reduces the pixelation. You have six attempts to identify the club." },
      placeholder: { body: "This route is ready. The module will connect to the shared 10theGOAT data core.", label: "⚽ Module under construction" }
    },
    beta: { title: "10theGOAT is in Beta", intro: "The site is playable, but we're still refining names, badges, scores, performance and the mobile experience.", playable: "Playable now", playableText: "Guess the Player, Higher or Lower and Guess the Badge.", development: "In development", developmentText: "Football Grid, Career Mode, My XI, user accounts and global rankings.", scores: "Scores", scoresText: "During this Beta they are stored in this browser. When accounts arrive, scores will be linked to the user.", bug: "Found a bug?", bugText: "Tell us what you were doing, which browser you used and, if possible, attach a screenshot.", report: "Report on GitHub", back: "← Back to games" },
    legal: { eyebrow: "Beta information", privacy: { title: "Privacy", lead: "10theGOAT is in Beta and does not currently have user accounts.", sections: [["Game data", "Game scores and local statistics are stored in your browser's local storage (localStorage). You can remove them by clearing the site's data in your browser."], ["Database and infrastructure", "The games query football data stored in Supabase. Hosting and database infrastructure may process technical data needed to serve requests, such as IP addresses, technical logs and security data."], ["Analytics and advertising", "This Beta does not include proprietary advertising analytics or user profiling by default."], ["Before final launch", "The site operator's identity and contact details must be completed in the final legal version before any commercial or monetised launch."]] }, cookies: { title: "Cookies and local storage", sections: [["", "10theGOAT does not currently set its own advertising or analytics cookies in this Beta."], ["localStorage", "The games use browser local storage to retain Beta scores, records and statistics. It is not a cookie and is not automatically sent to the server with each request."], ["Technical services", "The hosting provider or external services needed to serve the site may use their own technical mechanisms under their policies."], ["Future features", "If we add analytics, advertising, accounts or technologies that require consent, we will update this information and add a consent system where required."]] }, notice: { title: "Legal notice", sections: [["", "10theGOAT is an online football games project currently in Beta."], ["Content", "Third-party names, trademarks, badges and images belong to their respective owners. They appear in the Beta for identification within the games."], ["Availability", "As this is a Beta, features, scores, data and rules may change, reset or become unavailable during development."], ["Operator details", "HUMAN REVIEW REQUIRED: the site operator's legal identity and an appropriate contact channel must be added here before the domain is opened publicly."]] } },
    notFound: { title: "Offside.", body: "This page does not exist or has not taken the field yet.", back: "Back to home" }
  },
  fr: {
    languageName: "Français", nav: { home: "Accueil", games: "Jeux", beta: "Bêta", main: "Navigation principale", legal: "Informations légales", privacy: "Confidentialité", cookies: "Cookies", notice: "Mentions légales", feedback: "Avis", language: "Langue" },
    meta: { title: "Jeux de football en ligne", description: "Des jeux de football en ligne pour tester vos connaissances : Devinez le joueur, Plus ou Moins, Devinez l'écusson et plus encore.", shortDescription: "Testez vos connaissances du football avec des défis et mini-jeux gratuits." },
    home: { alt: "10theGOAT · Jeux de football en ligne", eyebrow: "10theGOAT Arena", title: "Ici aussi, on joue au football.", intro: "Choisissez votre défi, prouvez vos connaissances du football et battez votre meilleur score.", play: "Commencer à jouer", beta: "Explorer les jeux", version: "Arena", games: "Jeux", all: "Voir tout →" },
    catalog: { title: "Tous les jeux" }, status: { available: "Disponible", soon: "Bientôt disponible" },
    games: {
      higherLower: { title: "Plus ou Moins", description: "Comparez les statistiques des footballeurs et réalisez la plus longue série possible.", meta: "Comparez les buts de saisons réelles et réalisez la plus longue série possible.", eyebrow: "Statistiques réelles · clubs", intro: "Comparez des saisons réelles. Indiquez si le joueur de droite a marqué plus ou moins de buts que celui de gauche et construisez votre série." },
      wordle: { title: "Devinez le joueur", description: "Wordle football : six essais pour trouver le nom du joueur lettre par lettre.", meta: "Wordle football : trouvez le joueur en six essais.", eyebrow: "Wordle football", intro: "Six essais. Une lettre verte est bien placée ; une jaune figure dans le nom, mais ailleurs. Les accents ne comptent pas." },
      grid: { title: "Football Grid", description: "Croisez clubs, sélections et conditions pour trouver des joueurs valides." }, career: { title: "Mode Carrière", description: "Créez un joueur et simulez toute sa carrière, ses transferts, titres, sélections et son héritage." }, eleven: { title: "Mon XI", description: "Construisez votre onze idéal avec un budget, des contraintes et des cartes de joueurs." },
      badge: { title: "Devinez l'écusson", description: "Identifiez le club grâce à un écusson très pixelisé qui devient plus net à chaque essai.", meta: "Identifiez le club à mesure que son écusson se dévoile.", eyebrow: "Écussons de clubs", intro: "L'écusson est presque méconnaissable au départ. Chaque erreur réduit la pixellisation. Vous avez six essais pour trouver le club." },
      placeholder: { body: "Cette route est prête. Ce module sera connecté au socle de données commun de 10theGOAT.", label: "⚽ Module en construction" }
    },
    beta: { title: "10theGOAT est en Bêta", intro: "Le site est jouable, mais nous affinons encore les noms, écussons, scores, performances et l'expérience mobile.", playable: "Jouable maintenant", playableText: "Devinez le joueur, Plus ou Moins et Devinez l'écusson.", development: "En développement", developmentText: "Football Grid, Mode Carrière, Mon XI, comptes utilisateur et classements mondiaux.", scores: "Scores", scoresText: "Pendant cette Bêta, ils sont enregistrés dans ce navigateur. Avec les comptes, ils seront associés à l'utilisateur.", bug: "Vous avez trouvé un bug ?", bugText: "Indiquez-nous ce que vous faisiez, le navigateur utilisé et joignez si possible une capture d'écran.", report: "Signaler sur GitHub", back: "← Retour aux jeux" },
    legal: { eyebrow: "Informations Bêta", privacy: { title: "Confidentialité", lead: "10theGOAT est en Bêta et ne propose actuellement aucun compte utilisateur.", sections: [["Données de jeu", "Les scores et statistiques locales sont enregistrés dans le stockage local de votre navigateur (localStorage). Vous pouvez les supprimer en effaçant les données du site."], ["Base de données et infrastructure", "Les jeux consultent des données footballistiques stockées dans Supabase. L'infrastructure d'hébergement et de base de données peut traiter les données techniques nécessaires aux requêtes, notamment les adresses IP, journaux techniques et données de sécurité."], ["Analyse et publicité", "Cette Bêta n'intègre par défaut aucun outil propriétaire d'analyse publicitaire ni profilage utilisateur."], ["Avant le lancement final", "L'identité et les coordonnées de l'exploitant du site devront être ajoutées à la version légale définitive avant tout lancement commercial ou monétisé."]] }, cookies: { title: "Cookies et stockage local", sections: [["", "10theGOAT ne dépose actuellement aucun cookie publicitaire ou analytique propre dans cette Bêta."], ["localStorage", "Les jeux utilisent le stockage local du navigateur pour conserver les scores, records et statistiques de la Bêta. Ce n'est pas un cookie et ces données ne sont pas automatiquement envoyées au serveur à chaque requête."], ["Services techniques", "L'hébergeur ou les services externes nécessaires au fonctionnement du site peuvent utiliser leurs propres mécanismes techniques conformément à leurs politiques."], ["Fonctionnalités futures", "Si nous ajoutons des outils d'analyse, de la publicité, des comptes ou des technologies nécessitant un consentement, nous actualiserons ces informations et ajouterons un système de consentement si nécessaire."]] }, notice: { title: "Mentions légales", sections: [["", "10theGOAT est un projet de jeux de football en ligne actuellement en Bêta."], ["Contenu", "Les noms, marques, écussons et images de tiers appartiennent à leurs propriétaires respectifs. Leur présence dans la Bêta sert à l'identification au sein des jeux."], ["Disponibilité", "Cette version étant une Bêta, les fonctionnalités, scores, données et règles peuvent évoluer, être réinitialisés ou devenir indisponibles pendant le développement."], ["Informations sur l'exploitant", "RÉVISION HUMAINE REQUISE : l'identité légale de l'exploitant et un moyen de contact approprié doivent être ajoutés ici avant l'ouverture publique du domaine."]] } },
    notFound: { title: "Hors-jeu.", body: "Cette page n'existe pas ou n'est pas encore entrée sur le terrain.", back: "Retour à l'accueil" }
  },
} as const;

type Widen<T> = T extends string ? string : T extends readonly (infer U)[] ? readonly Widen<U>[] : T extends object ? { readonly [K in keyof T]: Widen<T[K]> } : T;
export type Dictionary = Widen<(typeof dictionaries)["es"]>;
