import bank from "../../data/timeline/challenges.json";
export type Locale = "es" | "en" | "fr";
export type Translation = Record<Locale, string>;
export type TimelineEvent = { id: string; year: number; date?: string; text: Translation };
export type TimelineChallenge = { id: string; category: Translation; title: Translation; events: TimelineEvent[]; explanation: Translation; source: string };
export const timelineChallenges: TimelineChallenge[] = bank;

export const timelineCopy={
 es:{title:"ORDENA LA HISTORIA",description:"Coloca cinco hitos futbolísticos en su orden cronológico.",intro:"Mueve las tarjetas hasta reconstruir la historia, luego comprueba tu respuesta.",position:"Posición",up:"Subir",down:"Bajar",check:"Comprobar orden",correct:"Orden perfecto",result:"Resultado",exact:"posiciones correctas",solution:"Orden correcto",next:"Siguiente historia",again:"Empezar de nuevo",points:"Puntos",best:"Mejor puntuación",rules:"Cómo se juega",rulesText:"Ordena del acontecimiento más antiguo al más reciente. Cada posición exacta vale 20 puntos. Tras comprobar, se muestra siempre el orden correcto con sus fechas.",storage:"No se pudo guardar el progreso; puedes seguir jugando."},
 en:{title:"ORDER HISTORY",description:"Place five football milestones in chronological order.",intro:"Move the cards to rebuild history, then check your answer.",position:"Position",up:"Move up",down:"Move down",check:"Check order",correct:"Perfect order",result:"Result",exact:"correct positions",solution:"Correct order",next:"Next story",again:"Start again",points:"Points",best:"Best score",rules:"How to play",rulesText:"Order the events from oldest to newest. Every exact position is worth 20 points. After checking, the correct order and dates are always revealed.",storage:"Progress could not be saved; you can keep playing."},
 fr:{title:"ORDONNEZ L'HISTOIRE",description:"Placez cinq jalons du football dans l'ordre chronologique.",intro:"Déplacez les cartes pour reconstruire l'histoire, puis vérifiez votre réponse.",position:"Position",up:"Monter",down:"Descendre",check:"Vérifier l'ordre",correct:"Ordre parfait",result:"Résultat",exact:"positions correctes",solution:"Ordre correct",next:"Histoire suivante",again:"Recommencer",points:"Points",best:"Meilleur score",rules:"Comment jouer",rulesText:"Classez les événements du plus ancien au plus récent. Chaque position exacte vaut 20 points. Après validation, l'ordre correct et les dates sont toujours révélés.",storage:"La progression n'a pas pu être enregistrée ; vous pouvez continuer."}
} as const;
