import type { CareerState, PlayerBlocks } from "./types.ts";

export type DecisionChoice={id:string;label:string;effects:Partial<PlayerBlocks>&{reputation?:number;family?:number};chance?:number;riskText?:string};
export type CareerDecision={id:string;title:string;choices:[DecisionChoice,DecisionChoice]};
const d=(id:string,title:string,yes:string,no:string,effects:DecisionChoice["effects"],chance?:number,riskText?:string):CareerDecision=>({id,title,choices:[{id:"yes",label:yes,effects,chance,riskText},{id:"no",label:no,effects:{}}]});
export const CAREER_DECISIONS:CareerDecision[]=[
d("extra","Entrenar después del horario","Hacerlo","Descansar",{technical:2,form:-2}),d("gym","Añadir trabajo de gimnasio","Aceptar","Mantener el plan",{physical:2,form:-1}),d("video","Estudiar vídeos de rivales","Estudiarlos","Desconectar",{mentality:2,form:-1}),d("weak-foot","Practicar la pierna débil","Practicar","No cambiar",{technical:2}),d("position","Probar una nueva función táctica","Aceptar","Seguir igual",{mentality:2,technical:-1}),
d("coach","Contratar entrenador personal","Contratarlo","Rechazar",{technical:1,physical:1}),d("rest","Priorizar la recuperación","Recuperar","Entrenar",{form:3,technical:-1}),d("pain","Jugar con molestias","Jugar","Parar",{reputation:2,form:-4},55,"Las molestias pueden empeorar"),d("hide-injury","Ocultar una lesión","Ocultarla","Informar",{reputation:1,form:-5},40,"Puede convertirse en lesión grave"),d("ask-rest","Pedir descanso","Pedirlo","Seguir",{form:3,reputation:-1}),
d("injection","Aceptar una infiltración legal","Aceptar","No arriesgar",{form:2,physical:-2},55,"Puede agravar la lesión"),d("diet","Cambiar radicalmente la dieta","Cambiarla","Mantenerla",{physical:2,form:-1},65,"La adaptación puede fallar"),d("commercial","Dormir menos por actos comerciales","Aceptar actos","Priorizar sueño",{reputation:3,form:-3}),d("physio","Contratar fisioterapeuta propio","Contratarlo","No hacerlo",{physical:1,form:2}),d("all-games","Jugar todos los partidos","Jugar todo","Rotar",{reputation:2,form:-3}),
d("doping","Te ofrecen suplementos prohibidos","Tomarlos","Rechazarlos",{physical:4,reputation:-35,form:-12},25,"75% de ser descubierto"),d("report-doping","Denunciar una oferta de dopaje","Denunciar","Callar",{reputation:3,mentality:2}),d("party","Salir de fiesta antes de un partido","Salir","Quedarte en casa",{form:-4,mentality:-1},45,"Puede trascender al club"),d("strict","Llevar una vida estrictamente profesional","Comprometerte","Ser flexible",{physical:2,mentality:2,form:-1}),d("starter","Pedir ser titular","Exigir minutos","Esperar",{reputation:1,form:-1},60,"El entrenador puede reaccionar mal"),
d("rotation","Aceptar un papel de rotación","Aceptar","Reclamar",{mentality:2,reputation:-1}),d("loan","Pedir una cesión","Pedirla","Quedarte",{reputation:-1,form:1}),d("reject-loan","Rechazar una cesión","Rechazar","Aceptar",{family:2,reputation:-1}),d("renew","Renovar con el club formador","Renovar","Esperar",{family:4,reputation:-1}),d("force","Forzar un traspaso","Forzarlo","Negociar",{reputation:-4,form:-2}),
d("contract","Terminar contrato","Esperar","Renovar",{reputation:2,form:-1}),d("minutes","Elegir club por minutos","Priorizar minutos","Priorizar prestigio",{form:2,reputation:-1}),d("prestige","Elegir club por prestigio","Priorizar prestigio","Priorizar minutos",{reputation:3,form:-2}),d("money","Elegir la mejor oferta económica","Elegir dinero","Elegir proyecto",{reputation:-2,family:2}),d("home","Regresar al país de origen","Volver","Continuar fuera",{family:8,reputation:-2}),
d("number","Ceder tu dorsal","Cederlo","Conservarlo",{mentality:2,reputation:-1}),d("demand-number","Exigir conservar tu dorsal","Exigirlo","Negociar",{reputation:2,mentality:-1}),d("mentor","Ayudar a una joven promesa","Ayudar","Competir",{mentality:3,reputation:1}),d("rival","Competir agresivamente con un compañero","Competir","Cooperar",{form:1,mentality:-2}),d("support-coach","Apoyar públicamente al entrenador","Apoyarlo","Ser neutral",{reputation:2,form:1},70,"Puede ser destituido"),
d("criticise","Criticar la táctica públicamente","Criticar","Hablar en privado",{reputation:-3,mentality:1}),d("captain","Aceptar la capitanía","Aceptar","Rechazar",{mentality:3,reputation:2,form:-1}),d("penalty","Lanzar un penalti decisivo","Lanzarlo","Cederlo",{reputation:4,form:3},72,"Fallar dañará tu confianza"),d("cede-penalty","Ceder un penalti a un compañero","Cederlo","Lanzarlo",{mentality:2,reputation:-1}),d("final-injured","Jugar una final lesionado","Jugar","Descansar",{reputation:5,form:-6,physical:-2},45,"Riesgo físico extremo"),
d("club-country","Priorizar el club sobre la selección","Priorizar club","Viajar",{form:3,reputation:-3}),d("country-pain","Viajar con la selección con molestias","Viajar","Recuperar",{reputation:4,form:-4},55,"Puede causar lesión"),d("country-break","Renunciar temporalmente a la selección","Renunciar","Continuar",{form:4,reputation:-4}),d("nationality","Cambiar de nacionalidad deportiva","Cambiar","Mantener",{reputation:2,family:-4}),d("social","Responder una provocación en redes","Responder","Ignorar",{reputation:-2,mentality:-2},40,"Puede haber sanción"),
d("silence","Guardar silencio ante una polémica","Callar","Responder",{mentality:1,reputation:-1}),d("apology","Admitir un error públicamente","Admitirlo","Negarlo",{reputation:3,mentality:2}),d("agent","Cambiar de representante","Cambiar","Continuar",{reputation:2,family:-1},60,"El nuevo agente puede no cumplir"),d("media","Conceder una entrevista polémica","Concederla","Rechazar",{reputation:4,mentality:-2},50,"Puede dividir a la afición"),d("charity","Crear una fundación","Crearla","Esperar",{reputation:3,family:2}),
];
export function decisionFor(state:CareerState){return CAREER_DECISIONS[Math.abs(state.seed+state.year*17)%CAREER_DECISIONS.length]}
