import type { CareerState, PlayerBlocks } from "./types.ts";
import { NATIONALITIES } from "./clubs.ts";
export type DecisionEffects=Partial<PlayerBlocks>&{reputation?:number;family?:number};
export type DecisionChoice={id:string;label:string;effects:DecisionEffects;chance?:number;riskText?:string};
export type CareerDecision={id:string;title:string;description:string;choices:[DecisionChoice,DecisionChoice];available?:(s:CareerState)=>boolean};
type Row=[string,string,string,string,string,DecisionEffects,number?,string?,CareerDecision["available"]?];
const few=(s:CareerState)=>(s.seasons.at(-1)?.minutes??0)<900,many=(s:CareerState)=>(s.seasons.at(-1)?.minutes??0)>2400,veteran=(s:CareerState)=>s.player.age>=30;
const rows:Row[]=[
["extra","El estadio se queda a oscuras","El utillero te deja entrenar una hora más, pero mañana hay sesión doble.","Seguir entrenando","Irme a descansar",{technical:2,form:-2}],
["gym","Un plan físico solo para ti","El preparador promete más potencia a cambio de llegar más cargado al fin de semana.","Añadir gimnasio","Mantener el plan",{physical:2,form:-1}],
["video","Cuarenta vídeos del rival","El analista quiere repasarlos esta noche, justo cuando necesitabas desconectar.","Estudiarlos","Descansar",{mentality:2,form:-1}],
["weak-foot","La pierna mala ya no se esconde","El técnico pide que dediques cada final de sesión a mejorarla.","Practicarla","Seguir igual",{technical:2}],
["position","Te quieren en otra posición","Puede abrirte el once, pero tendrás que reaprender movimientos.","Aceptar el reto","Seguir en mi puesto",{mentality:2,technical:-1}],
["coach","Un entrenador personal llama","Promete sesiones a medida fuera del club y resultados rápidos.","Contratarlo","Confiar en el club",{technical:1,physical:1}],
["rest","El cuerpo pide una tregua","Los datos muestran fatiga antes de una semana decisiva.","Recuperarme","Seguir entrenando",{form:3,technical:-1}],
["pain","El médico recomienda parar","Puedes jugar con molestias, pero un mal giro complicaría la temporada.","Jugar","Parar",{reputation:2,form:-4},55,"LAS MOLESTIAS PUEDEN EMPEORAR"],
["hide-injury","Nadie ha visto la lesión","Callar mantiene tu puesto; si empeora, el club sabrá que mentiste.","Ocultarla","Informar",{reputation:1,form:-5},40,"RIESGO DE LESIÓN GRAVE"],
["ask-rest","Necesitas respirar","Pedir descanso puede sentar mal al entrenador.","Pedirlo","Seguir disponible",{form:3,reputation:-1}],
["injection","Una infiltración antes del derbi","Es legal, aunque el médico no garantiza cómo responderá tu cuerpo.","Aceptar","No arriesgar",{form:2,physical:-2},55,"PUEDE AGRAVAR LA LESIÓN"],
["diet","Tu nutricionista quiere cambiarlo todo","El plan puede mejorar tu físico, pero la adaptación será incómoda.","Cambiar la dieta","Mantenerla",{physical:2,form:-1},65,"PUEDE FALLAR"],
["commercial","La marca quiere rodar de madrugada","Ganarás visibilidad, pero perderás sueño antes del partido.","Aceptar","Priorizar sueño",{reputation:3,form:-3}],
["physio","Un fisio de confianza queda libre","Podría cuidar tu cuerpo a diario sin interferir con el club.","Contratarlo","No hacerlo",{physical:1,form:2}],
["all-games","No quieres perderte un minuto","El técnico acepta si asumes toda la fatiga acumulada.","Jugarlo todo","Rotar",{reputation:2,form:-3}],
["doping","Te ofrecen suplementos prohibidos","Un intermediario promete una mejora inmediata y asegura que nadie lo detectará.","Tomarlos","Rechazarlos",{physical:4,reputation:-35,form:-12},25,"75% DE SER DESCUBIERTO"],
["report-doping","Has identificado al intermediario","La federación pide tu testimonio y te expondrá durante semanas.","Denunciar","Callar",{reputation:3,mentality:2}],
["party","Fiesta antes del partido","Hay periodistas siguiendo cada movimiento del equipo.","Salir","Quedarme en casa",{form:-4,mentality:-1},45,"PUEDE TRASCENDER"],
["strict","Vida de atleta total","Mejorarás hábitos, aunque tanta disciplina también puede agotarte.","Comprometerme","Buscar equilibrio",{physical:2,mentality:2,form:-1}],
["starter","Quieres una conversación incómoda","Crees que mereces ser titular y el técnico detesta los ultimátums.","Exigir minutos","Esperar",{reputation:1,form:-1},60,"PUEDE REACCIONAR MAL",few],
["rotation","Te ofrecen un papel secundario","Tendrías minutos regulares, pero dejarías de pelear por el once.","Aceptar","Reclamar",{mentality:2,reputation:-1}],
["loan","Necesitas jugar cada domingo","Una cesión te daría continuidad lejos del club que apostó por ti.","Pedirla","Quedarme",{reputation:-1,form:1},undefined,undefined,few],
["reject-loan","El club quiere cederte","Tu familia prefiere que te quedes, aunque aquí apenas juegas.","Rechazarla","Aceptar",{family:2,reputation:-1},undefined,undefined,few],
["renew","Contrato sobre la mesa","Renovar sería lealtad, pero limitaría tus opciones inmediatas.","Renovar","Esperar",{family:4,reputation:-1}],
["force","Tu agente quiere romper la baraja","Forzar la salida acelerará el mercado; la afición no lo olvidará.","Forzar traspaso","Negociar",{reputation:-4,form:-2}],
["contract","Puedes marcharte libre","Cumplir el contrato te dará control a cambio de meses de tensión.","Llegar al final","Renovar",{reputation:2,form:-1}],
["minutes","Dos proyectos, dos caminos","Uno garantiza jugar; el otro ofrece un gran escaparate desde el banquillo.","Priorizar minutos","Elegir prestigio",{form:2,reputation:-1}],
["prestige","Un grande llama antes de tiempo","Tu nombre crecerá, pero la competencia será feroz.","Dar el salto","Elegir minutos",{reputation:3,form:-2}],
["money","Una oferta rompe el mercado","Tu familia quedaría asegurada, aunque el proyecto deportivo convence menos.","Elegir dinero","Elegir proyecto",{reputation:-2,family:2}],
["home","Desde casa te necesitan","Volver reforzaría a tu familia, pero reduciría tu exposición.","Volver","Continuar fuera",{family:8,reputation:-2}],
["number","Una promesa pide tu dorsal","Cedérselo uniría al vestuario, pero debilitaría tu marca.","Cederlo","Conservarlo",{mentality:2,reputation:-1}],
["mentor","Un juvenil se sienta a tu lado","Te pide ayuda para adaptarse y competirá directamente contigo.","Ayudarle","Marcar distancia",{mentality:3,reputation:1}],
["rival","Tu compañero te gana el puesto","Puedes convertir cada sesión en una batalla o colaborar.","Competir duro","Cooperar",{form:1,mentality:-2}],
["support-coach","El vestuario duda del técnico","Tu apoyo puede estabilizarlo, pero quizá no sobreviva a la semana.","Apoyarlo","Ser neutral",{reputation:2,form:1},70,"PUEDE SER DESTITUIDO"],
["criticise","La táctica te deja expuesto","Los micrófonos esperan una frase dura al terminar.","Criticar","Hablar en privado",{reputation:-3,mentality:1}],
["captain","Te entregan el brazalete","Liderar elevará tu peso y también tus obligaciones.","Aceptar","Rechazar",{mentality:3,reputation:2,form:-1}],
["penalty","Penalti en el descuento","El lanzador habitual te ofrece el balón y todo el estadio mira.","Lanzarlo","Cederlo",{reputation:4,form:3},72,"FALLAR DAÑARÁ TU CONFIANZA"],
["final-injured","La final empieza en una hora","No estás recuperado, pero quizá nunca vivas otra noche así.","Jugar","Descansar",{reputation:5,form:-6,physical:-2},45,"RIESGO FÍSICO EXTREMO"],
["club-country","Club o selección","El club pide que evites el viaje internacional para recuperarte.","Priorizar club","Viajar",{form:3,reputation:-3}],
["country-pain","Convocado con molestias","Representar a tu país da prestigio, pero el viaje puede empeorarte.","Viajar","Recuperarme",{reputation:4,form:-4},55,"PUEDE CAUSAR LESIÓN"],
["country-break","El calendario te asfixia","Una pausa internacional cuidaría tu cuerpo, aunque el país no lo entenderá.","Renunciar temporalmente","Continuar",{form:4,reputation:-4}],
["nationality","Otra selección te abre la puerta","El país donde juegas te ofrece defender sus colores antes de tu debut internacional.","Aceptar el cambio","Mantener la mía",{reputation:2,family:-4},undefined,undefined,s=>s.totals.internationalCaps===0&&s.club.country!==s.player.nationality],
["social","Una cuenta rival te provoca","Tu respuesta puede hacerse viral antes de terminar el entrenamiento.","Responder","Ignorar",{reputation:-2,mentality:-2},40,"PUEDE HABER SANCIÓN"],
["apology","Tus palabras molestaron","Una disculpa puede cerrar la herida; negarlo mantiene el conflicto.","Disculparme","Negarlo",{reputation:3,mentality:2}],
["agent","Tu agente ha perdido peso","Otro promete mejores clubes, aunque nadie garantiza que cumpla.","Cambiar","Continuar",{reputation:2,family:-1},60,"PUEDE NO CUMPLIR"],
["media","Entrevista sin filtros","La audiencia será enorme y cada frase puede incendiar la afición.","Concederla","Rechazarla",{reputation:4,mentality:-2},50,"PUEDE DIVIDIR"],
["charity","Tu barrio necesita ayuda","Crear una fundación exige tiempo, pero deja huella fuera del campo.","Crearla","Esperar",{reputation:3,family:2}],
["cede-penalty","Tu compañero necesita un gol","Puedes fortalecer el grupo o asumir tú la responsabilidad.","Dárselo","Lanzarlo",{mentality:2,reputation:-1}],
["demand-number","El club quiere tu dorsal","Puedes convertirlo en un pulso público o negociar.","Exigirlo","Negociar",{reputation:2,mentality:-1}],
["silence","Un rumor domina las portadas","Callar protege al vestuario, pero otros contarán la historia.","Callar","Responder",{mentality:1,reputation:-1}],
// 50 situaciones nuevas.
["father-director","Tu padre monta una escena","Se ha encarado con el director deportivo por tu falta de minutos.","Defenderle","Pedir disculpas",{family:5,reputation:-4,mentality:-1},undefined,undefined,few],
["mother-radio","Tu madre habla en la radio","Ha contado que no eres feliz y el vestuario comenta sus palabras.","Respaldarla","Desmarcarme",{family:4,reputation:-3}],
["leaked-chat","Se filtra el chat del equipo","Aparece un mensaje tuyo criticando a un compañero.","Admitirlo","Negarlo",{reputation:-2,mentality:2},65,"NEGARLO PUEDE EMPEORARLO"],
["fan-tattoo","Un fan se tatúa tu cara","Pide ayuda porque el retrato se parece más al entrenador.","Pagar el retoque","Invitarle al partido",{reputation:2,family:-1}],
["boots","Las botas nuevas te hacen daño","La marca exige estrenarlas en el derbi.","Usarlas","Elegir las antiguas",{reputation:2,form:-3},55,"PUEDEN LESIONARTE"],
["ultras","Los ultras te invitan a cenar","Quieren hablar del escudo, lejos de cámaras y del club.","Aceptar","Rechazar",{reputation:3,mentality:-1},70,"PUEDE FILTRARSE"],
["rival-shirt","Un rival pide tu camiseta","Tras perder, la foto puede parecer respeto o indiferencia.","Intercambiarla","Negarme",{mentality:2,reputation:-1}],
["academy-fine","Un juvenil no paga una multa","Puedes cubrirla en secreto o dejar que aprenda.","Pagarla","No intervenir",{mentality:2,family:1}],
["coach-wedding","El técnico se casa","La boda coincide con tu único fin de semana familiar.","Ir a la boda","Volver a casa",{reputation:2,family:-3}],
["captain-secret","El capitán quiere salir","El director deportivo pregunta si sabes algo.","Guardar secreto","Contarlo",{mentality:3,reputation:-2}],
["notebook","Encuentras la táctica rival","Nadie te ha visto recoger el cuaderno.","Entregarlo","Estudiarlo",{reputation:3,mentality:-2}],
["fake-injury","Te piden fingir una lesión","Evitarías viajar con la selección y llegarías fresco.","Aceptar","Negarme",{form:4,reputation:-5},60,"PUEDEN INVESTIGARTE"],
["derby-promise","Prometes un gol en el derbi","La frase enciende a la grada y multiplica la presión.","Prometerlo","Ser prudente",{reputation:3,mentality:-2},55,"SI FALLAS, HABRÁ CRÍTICAS"],
["plane","Un compañero alquila un avión","Llegarías antes, pero el club prohibió viajes privados.","Subirme","Viajar con el equipo",{form:2,reputation:-3},65,"PUEDE HABER SANCIÓN"],
["mental-health","Ya no disfrutas del fútbol","Pedir ayuda alimentará rumores, pero llevas semanas al límite.","Pedir ayuda","Ocultarlo",{mentality:5,form:2,reputation:-1}],
["boos","Tu propia grada te silba","Puedes responder al marcar o celebrar con calma.","Responder","Calmar la situación",{reputation:-4,mentality:2},45,"PUEDE HABER SANCIÓN"],
["haircut","Pierdes una apuesta","Debes aparecer con un corte ridículo en la presentación.","Cumplirla","Pagar la cena",{mentality:2,reputation:1}],
["language","No hablas el idioma","Las clases intensivas ocuparán tus tardes libres.","Estudiar","Usar traductor",{mentality:3,family:-1}],
["grandparent","Tu abuelo cumple noventa","La fiesta coincide con la concentración de semifinales.","Viajar","Concentrarme",{family:6,reputation:-2}],
["birth","El nacimiento se adelanta","Tu pareja está de parto durante el gran partido.","Ir al hospital","Jugar",{family:10,reputation:-3}],
["school","Quieres terminar tus estudios","El curso reducirá descanso, pero prepara tu futuro.","Matricularme","Aplazarlo",{mentality:3,form:-1}],
["streamer","Un famoso quiere jugar contigo","El directo será la noche antes del entrenamiento.","Aceptar","Rechazar",{reputation:3,form:-2}],
["documentary","Una plataforma quiere grabarlo todo","Habrá cámaras en casa y vestuario toda la temporada.","Abrir mis puertas","Protegerme",{reputation:5,family:-4}],
["crypto","Patrocinio demasiado bueno","El cheque es enorme y nadie explica de dónde sale.","Firmar","Rechazar",{family:3,reputation:-6},35,"LA EMPRESA PUEDE CAER"],
["referee","El árbitro admite su error","Puedes publicar su mensaje o aceptar la disculpa.","Publicarlo","Guardarlo",{reputation:2,mentality:-3}],
["young-captain","El vestuario duda de ti","Varios veteranos esperaban recibir tu brazalete.","Aceptar el reto","Cederlo",{mentality:4,reputation:-1}],
["old-role","Te quieren retrasar la posición","Perderías ataque, pero podrías alargar tu carrera.","Adaptarme","Mantenerme",{mentality:3,physical:-1},undefined,undefined,veteran],
["retirement-rumour","Dicen que vas a retirarte","El club exige que aclares tu futuro.","Desmentirlo","Dejar dudas",{reputation:2,mentality:-1},undefined,undefined,veteran],
["veteran-rest","Te reservan para grandes noches","Jugarías menos, pero llegarías fresco.","Aceptar","Exigir jugar",{form:4,reputation:-2},undefined,undefined,veteran],
["record","Estás a un partido del récord","Puedes jugar tocado o arriesgarte a perder la ocasión.","Forzar","Esperar",{reputation:4,form:-4},50,"PUEDE EMPEORAR",veteran],
["academy-money","La cantera pide ayuda","Puedes financiar instalaciones renunciando a una prima.","Invertir","Cobrar",{reputation:3,family:1}],
["coach-son","El hijo del técnico compite contigo","La prensa busca una acusación de favoritismo.","Cuestionarlo","Apoyarle",{reputation:-3,mentality:2}],
["debt","Un compañero pide dinero","Dice que es urgente, pero cambia de historia.","Prestarle","Avisar al capitán",{family:-2,mentality:2},45,"PUEDE NO DEVOLVERLO"],
["passport","Pierdes el pasaporte","Un empleado propone un atajo irregular para viajar.","Aceptar","Quedarme",{reputation:-4,form:2},40,"PUEDE HABER INVESTIGACIÓN"],
["snow","El campo está congelado","El técnico mantiene una sesión con riesgo de lesión.","Protestar","Entrenar",{mentality:2,reputation:-1}],
["trophy","Rompes un trofeo del club","Nadie te vio y un empleado podría cargar con la culpa.","Confesar","Callar",{reputation:2,mentality:2}],
["mascot","La mascota revela la táctica","Un niño publica el dibujo que le hiciste.","Asumir la culpa","Culpar al protocolo",{reputation:1,mentality:-1}],
["anthem","No cantas el himno","Las cámaras te enfocan y estalla el debate.","Explicarme","No responder",{reputation:2,mentality:-1}],
["charity-match","Partido benéfico en vacaciones","El seguro del club no cubriría una lesión.","Jugar","Solo donar",{reputation:4,form:-2},70,"RIESGO DE LESIÓN"],
["tattoo-sponsor","La marca pide un tatuaje temporal","La campaña será viral y la afición rival prepara bromas.","Aceptar","Rechazar",{reputation:3,mentality:-1}],
["save-coach","Puedes salvar al entrenador","La directiva escucha a los líderes antes de decidir.","Defenderle","No intervenir",{reputation:2,mentality:-2},55,"SI FALLA, TE SEÑALARÁN"],
["bonus","Recibes una prima extraordinaria","Los canteranos no cobran y el vestuario debate repartirla.","Compartir","Quedármela",{mentality:3,family:-1}],
["empty-stadium","La grada está sancionada","Puedes ayudar a que entren niños al próximo partido.","Pagar parte","No intervenir",{reputation:4,family:-1}],
["fake-offer","Tu agente filtra una oferta falsa","Quiere presionar al club para renovar.","Seguir el juego","Desmentirlo",{reputation:-3,family:1},40,"PUEDEN DESCUBRIRLO"],
["bench-camera","Una cámara capta tu enfado","Arrojaste el peto al ser sustituido.","Disculparme","Justificarme",{mentality:2,reputation:-1}],
["keeper","Falta el portero suplente","Te piden ponerte bajo palos para terminar la sesión.","Aceptar","Seguir mi rutina",{mentality:2,form:1}],
["family-ultimatum","Tu familia exige respuestas","Tras otro mes en el banquillo quieren reunirse con el club.","Permitirlo","Frenarles",{family:4,reputation:-3},undefined,undefined,few],
["overplayed","El vestuario teme otra lesión","Eres quien más juega y te piden reclamar rotaciones.","Alzar la voz","Hablar en privado",{form:3,reputation:-2},undefined,undefined,many],
["farewell","El capitán anuncia su marcha","Te pide proteger a los jóvenes cuando se vaya.","Aceptar su legado","Centrarme en jugar",{mentality:4,form:-1}],
["pet-rescue","Un perro invade el entrenamiento","Puedes adoptarlo, aunque tu familia no esperaba otra responsabilidad.","Adoptarlo","Buscarle un hogar",{reputation:2,family:-1}],
];
function alternativeEffects(effects:DecisionEffects):DecisionEffects{
  return Object.fromEntries(Object.entries(effects).map(([key,value])=>[key,-Math.sign(value)*Math.min(3,Math.max(1,Math.ceil(Math.abs(value)/2)))])) as DecisionEffects;
}
export const CAREER_DECISIONS:CareerDecision[]=rows.map(([id,title,description,yes,no,effects,chance,riskText,available])=>({id,title,description,choices:[{id:"yes",label:yes,effects,chance,riskText},{id:"no",label:no,effects:alternativeEffects(effects)}],available}));
export function targetNationalityFor(s:CareerState){return s.totals.internationalCaps===0&&s.club.country!==s.player.nationality&&NATIONALITIES.includes(s.club.country as (typeof NATIONALITIES)[number])?s.club.country:null}
export function decisionFor(s:CareerState){const pool=CAREER_DECISIONS.filter(x=>!x.available||x.available(s));return pool[Math.abs(s.seed+s.year*17)%pool.length]}
