// Operational disclosures shared by the three dictionaries. Operator identity,
// legal bases and retention for hosted data still require the owner's review.
export const legalCopy = {
  es: {
    privacy: { title: "Privacidad", lead: "10theGOAT ofrece juegos de fútbol, almacenamiento de partidas y funciones opcionales de cuenta.", sections: [
      ["Partidas y preferencias", "Guardamos puntuaciones, logros y preferencias en localStorage, y el estado de algunas partidas en sessionStorage. Puedes borrar estos datos desde tu navegador. La cookie 10tg-locale conserva el idioma elegido durante un año."],
      ["Cuentas e infraestructura", "Si inicias sesión, Supabase gestiona la autenticación y permite guardar información del perfil y partidas de Carrera en la nube. El proveedor de acceso elegido comparte los datos necesarios para identificar tu cuenta. El alojamiento y Supabase pueden tratar direcciones IP y registros técnicos para prestar y proteger el servicio."],
      ["Publicidad y medición", "Cuando la publicidad está activada, utilizamos Google AdSense. Google y sus socios pueden tratar direcciones IP, identificadores, información del dispositivo e interacciones con anuncios para servir y medir publicidad y, según tus preferencias y las condiciones aplicables, personalizarla. Consultamos los informes del proveedor; esta integración no añade Google Analytics ni seguimiento propio de partidas."],
      ["Tus preferencias", "El panel de consentimiento de Google permite aceptar, rechazar o gestionar las finalidades y los proveedores que muestra. Puedes volver a abrirlo desde Preferencias de privacidad cuando esté disponible. Rechazar el consentimiento no impide jugar. El panel identifica a los socios publicitarios y explica sus finalidades."],
      ["Conservación y derechos", "Los datos locales permanecen hasta que los borres o finalice la sesión de almacenamiento correspondiente. Los datos de cuenta y los tratados por terceros tienen sus propias condiciones de conservación. Antes del lanzamiento comercial se completarán la identidad y el contacto del responsable, las bases jurídicas, los plazos de conservación, las transferencias y el procedimiento para ejercer tus derechos."]
    ] },
    cookies: { title: "Cookies y almacenamiento local", sections: [
      ["Idioma y aviso", "10tg-locale recuerda el idioma que seleccionas durante un ano. 10tg-cookie-notice registra que has visto el aviso durante un ano; no autoriza publicidad ni analitica."],
      ["Partidas y cuenta", "localStorage conserva récords, preferencias y datos de partidas; sessionStorage permite continuar determinadas rondas dentro de la sesión del navegador. La autenticación de Supabase también puede conservar la sesión de tu cuenta en el navegador. Borrar los datos del sitio puede eliminar partidas locales y cerrar tu sesión."],
      ["Publicidad", "Si AdSense está activado, Google y sus socios pueden usar cookies y tecnologías similares para servir, medir y personalizar anuncios según las preferencias y las condiciones aplicables. La CMP de Google conserva tu elección. Los proveedores y las finalidades se consultan en su panel; el inventario y las duraciones de las tecnologías activas deben verificarse al configurar la cuenta."],
      ["Cambiar tu elección", "Usa Preferencias de privacidad para volver a abrir el panel de Google cuando esté disponible. Puedes rechazar o modificar tu consentimiento y seguir jugando. No instalamos una herramienta propia de analítica con esta integración."]
    ] },
  },
  en: {
    privacy: { title: "Privacy", lead: "10theGOAT offers football games, saved game progress and optional account features.", sections: [
      ["Games and preferences", "We store scores, achievements and preferences in localStorage, and some game sessions in sessionStorage. You can remove this data in your browser. The 10tg-locale cookie remembers your selected language for one year."],
      ["Accounts and infrastructure", "If you sign in, Supabase handles authentication and supports storing profile information and Career saves in the cloud. Your chosen sign-in provider shares the data needed to identify your account. Hosting and Supabase may process IP addresses and technical logs to deliver and protect the service."],
      ["Advertising and measurement", "When advertising is enabled, we use Google AdSense. Google and its partners may process IP addresses, identifiers, device information and ad interactions to serve and measure ads and, depending on your preferences and applicable conditions, personalize them. We use the provider's reports; this integration adds neither Google Analytics nor our own game tracking."],
      ["Your choices", "Google's consent panel lets you accept, reject or manage the purposes and providers it displays. You can reopen it from Privacy preferences when available. Refusing consent does not prevent you from playing. The panel identifies advertising partners and explains their purposes."],
      ["Retention and rights", "Local data remains until you delete it or the corresponding storage session ends. Account data and data processed by third parties have their own retention conditions. Before commercial launch, the operator's identity and contact details, legal bases, retention periods, transfers and rights request procedure will be completed."]
    ] },
    cookies: { title: "Cookies and local storage", sections: [
      ["Language and notice", "10tg-locale remembers your selected language (ES, EN or FR) for one year. 10tg-cookie-notice records that you have seen the cookie notice for one year; it does not authorize advertising or analytics."],
      ["Games and account", "localStorage retains records, preferences and game data; sessionStorage lets you continue certain rounds within your browser session. Supabase authentication may also retain your account session in your browser. Clearing site data can remove local saves and sign you out."],
      ["Advertising", "If AdSense is enabled, Google and its partners may use cookies and similar technologies to serve, measure and personalize ads according to your preferences and applicable conditions. Google's CMP stores your choice. Providers and purposes are available in its panel; the inventory and lifetimes of active technologies must be verified during account setup."],
      ["Change your choice", "Use Privacy preferences to reopen Google's panel when available. You can refuse or change consent and keep playing. This integration does not install our own analytics tool."]
    ] },
  },
  fr: {
    privacy: { title: "Confidentialité", lead: "10theGOAT propose des jeux de football, des sauvegardes de parties et des fonctions de compte facultatives.", sections: [
      ["Parties et préférences", "Nous conservons les scores, succès et préférences dans localStorage, et certaines parties dans sessionStorage. Vous pouvez effacer ces données dans votre navigateur. Le cookie 10tg-locale mémorise la langue choisie pendant un an."],
      ["Comptes et infrastructure", "Si vous vous connectez, Supabase gère l'authentification et permet de conserver des informations de profil et des sauvegardes Carrière dans le cloud. Le fournisseur de connexion choisi partage les données nécessaires pour identifier votre compte. L'hébergeur et Supabase peuvent traiter des adresses IP et des journaux techniques pour fournir et protéger le service."],
      ["Publicité et mesure", "Lorsque la publicité est activée, nous utilisons Google AdSense. Google et ses partenaires peuvent traiter des adresses IP, identifiants, informations sur l'appareil et interactions publicitaires pour diffuser et mesurer les annonces et, selon vos préférences et les conditions applicables, les personnaliser. Nous consultons les rapports du fournisseur ; cette intégration n'ajoute ni Google Analytics ni suivi de parties propre au site."],
      ["Vos choix", "Le panneau de consentement de Google permet d'accepter, de refuser ou de gérer les finalités et fournisseurs affichés. Vous pouvez le rouvrir depuis Préférences de confidentialité lorsqu'il est disponible. Refuser le consentement n'empêche pas de jouer. Le panneau identifie les partenaires publicitaires et explique leurs finalités."],
      ["Conservation et droits", "Les données locales restent présentes jusqu'à leur suppression ou à la fin de la session de stockage correspondante. Les données de compte et celles traitées par des tiers ont leurs propres conditions de conservation. Avant le lancement commercial, l'identité et les coordonnées de l'exploitant, les bases juridiques, durées de conservation, transferts et modalités d'exercice des droits seront complétés."]
    ] },
    cookies: { title: "Cookies et stockage local", sections: [
      ["Langue et avis", "10tg-locale memorise la langue choisie pendant un an. 10tg-cookie-notice enregistre que vous avez vu l avis cookies pendant un an ; il n autorise ni publicite ni analyse."],
      ["Parties et compte", "localStorage conserve les records, préférences et données de jeu ; sessionStorage permet de poursuivre certaines manches dans la session du navigateur. L'authentification Supabase peut également conserver votre session de compte dans le navigateur. Effacer les données du site peut supprimer des sauvegardes locales et vous déconnecter."],
      ["Publicité", "Si AdSense est activé, Google et ses partenaires peuvent utiliser des cookies et technologies similaires pour diffuser, mesurer et personnaliser les annonces selon vos préférences et les conditions applicables. La CMP de Google conserve votre choix. Les fournisseurs et finalités figurent dans son panneau ; l'inventaire et les durées des technologies actives doivent être vérifiés lors de la configuration du compte."],
      ["Modifier votre choix", "Utilisez Préférences de confidentialité pour rouvrir le panneau de Google lorsqu'il est disponible. Vous pouvez refuser ou modifier votre consentement et continuer à jouer. Cette intégration n'installe pas d'outil d'analyse propre au site."]
    ] },
  },
};
