-- 10 THE GOAT - Core football data model v1
-- PostgreSQL / Supabase

create extension if not exists pgcrypto;

create table if not exists public.countries (
  id bigint generated by default as identity primary key,
  name text not null unique,
  code text,
  flag_emoji text,
  continent text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.clubs (
  id bigint generated by default as identity primary key,
  name text not null,
  country_id bigint references public.countries(id) on delete set null,
  founded_year integer,
  is_national_team boolean not null default false,
  badge_url text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists clubs_country_id_idx on public.clubs(country_id);
create index if not exists clubs_name_idx on public.clubs(lower(name));

create table if not exists public.competitions (
  id bigint generated by default as identity primary key,
  name text not null,
  country_id bigint references public.countries(id) on delete set null,
  scope text not null default 'domestic' check (scope in ('domestic', 'continental', 'international')),
  competition_type text not null default 'league' check (competition_type in ('league', 'cup', 'super_cup', 'tournament', 'other')),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists competitions_country_id_idx on public.competitions(country_id);
create index if not exists competitions_name_idx on public.competitions(lower(name));

create table if not exists public.players (
  id bigint generated by default as identity primary key,
  display_name text not null,
  full_name text,
  first_name text,
  last_name text,
  birth_date date,
  nationality_country_id bigint references public.countries(id) on delete set null,
  height_cm smallint,
  weight_kg smallint,
  primary_position text,
  preferred_foot text check (preferred_foot is null or preferred_foot in ('left', 'right', 'both')),
  photo_url text,
  is_active boolean not null default true,
  is_retired boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists players_nationality_idx on public.players(nationality_country_id);
create index if not exists players_display_name_idx on public.players(lower(display_name));
create index if not exists players_birth_date_idx on public.players(birth_date);

-- Provider mappings. Internal IDs above remain the source of truth.
create table if not exists public.player_external_ids (
  player_id bigint not null references public.players(id) on delete cascade,
  provider text not null,
  external_id text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (player_id, provider),
  unique (provider, external_id)
);

create table if not exists public.club_external_ids (
  club_id bigint not null references public.clubs(id) on delete cascade,
  provider text not null,
  external_id text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (club_id, provider),
  unique (provider, external_id)
);

create table if not exists public.competition_external_ids (
  competition_id bigint not null references public.competitions(id) on delete cascade,
  provider text not null,
  external_id text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (competition_id, provider),
  unique (provider, external_id)
);

-- Historical relationship used heavily by Football Grid and Player Mystery.
create table if not exists public.player_club_seasons (
  id bigint generated by default as identity primary key,
  player_id bigint not null references public.players(id) on delete cascade,
  club_id bigint not null references public.clubs(id) on delete cascade,
  season_start_year integer not null check (season_start_year between 1800 and 2200),
  shirt_number smallint,
  is_current boolean not null default false,
  source_provider text,
  last_synced_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (player_id, club_id, season_start_year)
);

create index if not exists pcs_player_idx on public.player_club_seasons(player_id);
create index if not exists pcs_club_idx on public.player_club_seasons(club_id);
create index if not exists pcs_season_idx on public.player_club_seasons(season_start_year);

create table if not exists public.player_season_stats (
  id bigint generated by default as identity primary key,
  player_id bigint not null references public.players(id) on delete cascade,
  club_id bigint not null references public.clubs(id) on delete cascade,
  competition_id bigint not null references public.competitions(id) on delete cascade,
  season_start_year integer not null check (season_start_year between 1800 and 2200),
  appearances integer,
  starts integer,
  minutes integer,
  goals integer,
  assists integer,
  yellow_cards integer,
  red_cards integer,
  shots integer,
  shots_on_target integer,
  passes integer,
  key_passes integer,
  pass_accuracy numeric(5,2),
  tackles integer,
  interceptions integer,
  duels integer,
  duels_won integer,
  saves integer,
  goals_conceded integer,
  rating numeric(4,2),
  raw_stats jsonb,
  source_provider text,
  season_status text not null default 'unknown' check (season_status in ('current', 'completed', 'unknown')),
  last_synced_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (player_id, club_id, competition_id, season_start_year)
);

create index if not exists pss_player_idx on public.player_season_stats(player_id);
create index if not exists pss_club_idx on public.player_season_stats(club_id);
create index if not exists pss_competition_idx on public.player_season_stats(competition_id);
create index if not exists pss_season_idx on public.player_season_stats(season_start_year);

create table if not exists public.player_transfers (
  id bigint generated by default as identity primary key,
  player_id bigint not null references public.players(id) on delete cascade,
  from_club_id bigint references public.clubs(id) on delete set null,
  to_club_id bigint references public.clubs(id) on delete set null,
  transfer_date date,
  transfer_type text,
  fee_text text,
  source_provider text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists transfers_player_idx on public.player_transfers(player_id);
create index if not exists transfers_date_idx on public.player_transfers(transfer_date);

create table if not exists public.player_honours (
  id bigint generated by default as identity primary key,
  player_id bigint not null references public.players(id) on delete cascade,
  competition_id bigint references public.competitions(id) on delete set null,
  club_id bigint references public.clubs(id) on delete set null,
  competition_name_raw text not null,
  country_name_raw text,
  season_label text,
  place text,
  source_provider text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists honours_player_idx on public.player_honours(player_id);
create index if not exists honours_competition_idx on public.player_honours(competition_id);

-- Optional extended media catalogue. The primary player portrait and club badge
-- live directly in players.photo_url and clubs.badge_url for simple web rendering.
-- This table is reserved for alternate/owned assets and future provenance needs.
-- Competition logos are intentionally not part of the v1 model.
create table if not exists public.media_assets (
  id uuid primary key default gen_random_uuid(),
  player_id bigint references public.players(id) on delete cascade,
  club_id bigint references public.clubs(id) on delete cascade,
  asset_type text not null check (asset_type in ('portrait', 'badge', 'other')),
  provider text not null,
  provider_url text,
  storage_path text,
  mime_type text,
  width integer,
  height integer,
  checksum text,
  license_status text not null default 'unknown' check (license_status in ('owned', 'open_license', 'provider_supplied', 'permission_required', 'unknown')),
  license_notes text,
  is_primary boolean not null default false,
  last_synced_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint media_assets_single_owner check (
    (player_id is not null and club_id is null)
    or (player_id is null and club_id is not null)
  )
);

create index if not exists media_assets_player_idx on public.media_assets(player_id);
create index if not exists media_assets_club_idx on public.media_assets(club_id);
create unique index if not exists media_primary_player_idx
  on public.media_assets(player_id, asset_type)
  where player_id is not null and is_primary = true;
create unique index if not exists media_primary_club_idx
  on public.media_assets(club_id, asset_type)
  where club_id is not null and is_primary = true;

-- Sync bookkeeping prevents us from refreshing immutable historical data forever.
create table if not exists public.sync_state (
  id bigint generated by default as identity primary key,
  entity_type text not null,
  entity_id bigint,
  provider text not null,
  sync_key text not null,
  priority smallint not null default 5 check (priority between 1 and 10),
  last_synced_at timestamptz,
  next_sync_at timestamptz,
  last_status text,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (provider, sync_key)
);

create index if not exists sync_state_due_idx on public.sync_state(next_sync_at, priority);

-- Generic updated_at trigger.
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'countries', 'clubs', 'competitions', 'players',
    'player_external_ids', 'club_external_ids', 'competition_external_ids',
    'player_club_seasons', 'player_season_stats', 'player_transfers',
    'player_honours', 'media_assets', 'sync_state'
  ]
  loop
    execute format('drop trigger if exists set_updated_at on public.%I', table_name);
    execute format(
      'create trigger set_updated_at before update on public.%I for each row execute function public.set_updated_at()',
      table_name
    );
  end loop;
end;
$$;

-- Public web clients get read-only access. Imports will later use the service role server-side.
alter table public.countries enable row level security;
alter table public.clubs enable row level security;
alter table public.competitions enable row level security;
alter table public.players enable row level security;
alter table public.player_external_ids enable row level security;
alter table public.club_external_ids enable row level security;
alter table public.competition_external_ids enable row level security;
alter table public.player_club_seasons enable row level security;
alter table public.player_season_stats enable row level security;
alter table public.player_transfers enable row level security;
alter table public.player_honours enable row level security;
alter table public.media_assets enable row level security;
alter table public.sync_state enable row level security;

create policy "public read countries" on public.countries for select to anon, authenticated using (true);
create policy "public read clubs" on public.clubs for select to anon, authenticated using (true);
create policy "public read competitions" on public.competitions for select to anon, authenticated using (true);
create policy "public read players" on public.players for select to anon, authenticated using (true);
create policy "public read player club seasons" on public.player_club_seasons for select to anon, authenticated using (true);
create policy "public read player stats" on public.player_season_stats for select to anon, authenticated using (true);
create policy "public read transfers" on public.player_transfers for select to anon, authenticated using (true);
create policy "public read honours" on public.player_honours for select to anon, authenticated using (true);
create policy "public read media" on public.media_assets for select to anon, authenticated using (true);

-- Provider IDs and sync internals stay server-only by default.
